# generated by chatgpt as a tool to help me find a program i made but why not keep it here :)

import os
import re
import subprocess
import time

def is_utf8_file(file_path):
    try:
        with open(file_path, 'rb') as f:
            while chunk := f.read(1024):
                chunk.decode('utf-8')
        return True
    except (UnicodeDecodeError, OSError):
        return False

def search_string_in_files(folder, search_string):
    for root, _, files in os.walk(folder):
        for file in files:
            file_path = os.path.join(root, file)
            if is_utf8_file(file_path):
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        if re.search(re.escape(search_string), content):
                            print(f"Found in: {file_path}")
                            subprocess.run(["explorer", "/select,", os.path.abspath(file_path)])
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")
            else:
                print(f"Skipping non-UTF-8 file: {file_path}")
            
            time.sleep(0.01)

if __name__ == "__main__":
    folder_to_search = input("Enter the folder to search: ").strip()
    search_term = input("Enter the string to search for: ").strip()

    if os.path.isdir(folder_to_search):
        search_string_in_files(folder_to_search, search_term)
    else:
        print("Invalid folder path. Please try again.")
